### ISSUE TITLE
Error when subjected to fast repeated calls

### ISSUE THREAD

**Issue by pmos69** [mavam/vast#105]
Steps to reproduce:
```
terminal1: sudo vast -n -l 5 start -f

terminal2: while true; do vast show actors; done
```
Vast will crash after some seconds (usually less than a minute) with the following output:
```
...
:: key-value-store#8 got LIST: actors
:: node#6 shows actors
:: key-value-store#8 got LIST: actors
:: node#6 shows actors
:: key-value-store#8 got LIST: actors
:: node#6 shows actors
:: key-value-store#8 got LIST: q▒▒▒▒0t▒
*** Error in `:: node#6 shows actors
vast': corrupted double-linked list (not small): 0x00007fecd4017180 ***
```

**Comment by mavam** [comment]
With 25688993898af26141d8b193da784c2353c8fc60 I've silently slipped in a fix for reference-to-temporary bug. At this point I cannot reproduce the issue. Would you mind checking on your end whether the issue still persists? If not, we can close it.

**Comment by pmos69** [comment]
Can't reproduce it after 2568899.
Closing :)
