### ISSUE TITLE
Allow unordered input of fields (BRO format)

### ISSUE THREAD

**Issue by pmos69** [mavam/vast#110]
The input of the following bro file will fail (`:: index#15 failed to derive valid schema from event data`) because the order of the fields is not exactly the same:
```
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   Test
#open   2015-10-08-14-55-06
#fields f1      f2      f3
#types  string  string  string
v1      v2      v3
#close  2015-10-08-14-55-06
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   Test
#open   2015-10-08-14-55-06
#fields f1      f3      f2
#types  string  string  string
v1      v3      v2
#close  2015-10-08-14-55-06
```
(watch out - tabs are replaced with spaces when the text is posted here)
The fields are the same. Just in a different order.

Only really useful if #107 is implemented.

**Comment by mavam** [comment]
Yes, this is a problem. Up to this point, type equality, and in particular equality of records, depends on the field order. Issue #78 states this explicitly. What you observe as an artifact of this deficiency: the two types `Test` have a different signature, [which VAST currently cannot handle within the same partition](https://github.com/mavam/vast/blob/4017b58acd9311d60430c1ed7b1355e7b84cb038/src/vast/actor/index.cc#L387).

**Comment by pmos69** [comment]
Oh, didn't see #78.
I'll close this as a duplicate.
