### ISSUE TITLE
Fix saving of results to file system

### ISSUE THREAD

**Issue by sethhall** [mavam/vast#41]
When I go to save results from query mode...

````
[c6bdb2c0-9c2d-40d2-a878-68be13a689f9] saving result to vast/console/results/c6bdb2c0-9c2d-40d2-a878-68be13a689f9
[c6bdb2c0-9c2d-40d2-a878-68be13a689f9] saved 510 events
````

I get that result but there is no file there.  It would be nice if it output a full path for the file name too.

**Comment by mavam** [comment]
I'll address this as part of the CLI rewrite with SASH (#65).
