### ISSUE TITLE
Support a flexible distributed architecture

### ISSUE THREAD

**Issue by mavam** [mavam/vast#67]
To make VAST run on a cluster, we need a simple control pane to spawn components on nodes. The TRACKER is the central piece where each node connects to, and it should be able to dispatch commands to each node, e.g., to spawn a RECEIVER and wire it to a given ARCHIVE and INDEX.

This also relates #65 because we need a better interface to perform these tasks.

**Comment by Neverlord** [comment]
CAF has `remote_spawn` on its agenda, is this something you could utilize for this?

**Comment by mavam** [comment]
Yes, that sounds very useful.

It will also rely on actor-framework/actor-framework#204 and the direct connection topic branch that we've been working on.

**Comment by mavam** [comment]
The alternative to `remote_spawn` which I've envisioned so far would be to send the remote node a message to instruct it to `spawn` an actor there, and then send the actor handle to TRACKER. With `remote_spawn` that would probably a one-shot message from TRACKER to the node. Then I wonder, though, if nodes can "trap" such a message because spawning an actor would also mean that it needs to be integrated with the monitors and links to ensure proper shutdown and failure semantics.
