### ISSUE TITLE
Create self-contained JSON string of values

### ISSUE THREAD

**Issue by mavam** [mavam/vast#73]
When printing events as JSON, the internal value renders both data and type separately for space efficiency. Right now, JSON events look like this:

```json
{
  "id": 36478,
  "timestamp": 1430812815000000000,
  "value": {
    "data": [
      1430812815000000000,
      "195.47.235.100",
      6881,
      "213.52.131.0\/24",
      [
        6881,
        6939
      ],
      6939,
      "IGP",
      "195.47.235.100",
      0,
      0,
      "",
      "NAG",
      ""
    ],
    "type": "bgpdump::announcement"
  }
}
```
This is not a self-contained representation, because one needs to have full understanding of the type `bgpdump::announcement` in order to interpret the data. We should switch the JSON representation to a self-describing format.

**Comment by rs-schmidt** [comment]
I think we can change the data type from array to json object (dictionary) and add the schema type names as keys. 
for example:

```
{
  "id": 36478,
  "timestamp": 1430812815000000000,
  "value": {
    "data": {
      "timestamp": 1430812815000000000,
      "source_ip": "195.47.235.100",
      "source_as": 6881,
      "prefix": "213.52.131.0\/24",
      "as_path": [
        6881,
        6939
      ],
      "origin_as": 6939,
      "origin": "IGP",
      "nexthop": "195.47.235.100",
      "local_pref": 0,
      "med": 0,
      "community": "",
      "atomic_aggregate": "NAG",
      "aggregator": ""
    },
    "type": "bgpdump::announcement"
  }
}
```

**Comment by mavam** [comment]
While simple and clean, it does not work with type system in general. The problem is that JSON objects have no well-defined ordering, but VAST records have. For example, a `record { a: string, b: string }` is a different type from `record { b: string, a: string }` because the field names are part of the type signature.

So, the key question is whether we want to construct a 1-to-1 mapping between the JSON and the VAST representation. If we don't, your approach works just fine, Otherwise I'd suggest that we use a combination of arrays and dictionaries.

For now, I'd say we start with the simple route. Once we import events in JSON format, we can still add the more general style.

**Comment by mavam** [comment]
To give an example, what do you think of this value representation?

```json
{
    "data": [
    {
      "foo": "53\/udp"
    },
    {
      "bar": -42
    },
    {
      "baz": 4.2
    }
  ],
  "type": "record {foo: port, bar: int, baz: real}"
}
```

The array around `data` guarantees the ordering, whereas each element consists of a key equal to the record type.

**Comment by Fabrice7** [comment]
The representation rs-schmidt posted is less verbose and more pratical. Thus, if possible I would prefer to use mapping instead of a list. 

However, as long as we need an order of the values, the representation of ```data``` you proposed is the best solution to enable maintainable code. Since we do not have to depend on the order of a list which may change. But for ```type``` it is more practical to have a name to filter on. 
To show the order of ```data``` (a) a new field could be used (more verbose) or (b) it is left out (more parsing). I do not know which option is better. In our case, we will stream a lot of data thus more verbose is bad but on the other hand easier parsing sounds good as well.

**Comment by mavam** [comment]
> The representation rs-schmidt posted is less verbose and more pratical. Thus, if possible I would prefer to use mapping instead of a list.

How does your web interface work? Does it sequentially go through the JSON object or do you keep track of the full type elsewhere and "zip" the two together?

> However, as long as we need an order of the values, the representation of data you proposed is the best solution to enable maintainable code. Since we do not have to depend on the order of a list which may change. But for type it is more practical to have a name to filter on.

I hear you on the practical aspect. However, we need to bow to the JSON standard which does not guarantee an order of objects. The reason is because they're sometimes implemented as hash tables. That's why I'm leaning towards a representation that works the same with all JSON implementations.

I have one more proposal that relies on a zip implementation. [Seems like that's not too hard in JS](http://stackoverflow.com/q/4856717/1170277).

```json
{
  "data": ["53\/udp", -42, 4.2],
  "type": [{"foo": "port"}, {"bar": "int"}, {"baz": "real"}],
}
```

This would preserve the complete type information but keeps the data array short. (In this example, I assume that a type that starts with an array is always a record.)

@sethhall Do you have any opinions on this? I recall you were pushing on JSON support in the past.

**Comment by mavam** [comment]
All right, since we're moving away from ordered record semantics (see #78), let's go with the scheme proposed by @rs-schmidt.
