### ISSUE TITLE
Inconsistent query results 

### ISSUE THREAD

**Issue by pmos69** [mavam/vast#93]
Easiest way to describe the issue is by giving examples:
in an archive with bro::conn events, immediately after launching the daemon with  ```sudo vast -n -l 5 start -f```,
```vast export ascii -h 'service == nil'``` returns events correctly
```vast export ascii -h 'service == "ssh"'``` **returns 0 events (although events should be returned)**
```vast export ascii -h 'service == "dhcp"'``` **returns 0 events (although events should be returned)**
```vast export ascii -h 'service == "dns"'``` **returns 0 events (although events should be returned)**
```vast export ascii -h 'service != "ssh"'``` returns events correctly 

Imediately after restarting the daemon with  ```sudo vast -n -l 5 start -f```,
```vast export ascii -h 'service == "ssh"'``` returns events correctly
```vast export ascii -h 'service == "dhcp"'``` returns events correctly
```vast export ascii -h 'service == "dns"'``` returns events correctly
```vast export ascii -h 'service == nil'``` **returns 0 events (although events should be returned)**
```vast export ascii -h 'service != nil'``` returns events correctly 

Can be reproduced every time.
Many other variations possible, including using boolean expressions.

**Comment by mavam** [comment]
The partition cache was only the tip of the iceberg. The underlying bug was quite deep and I'm surprised it didn't show up before. Anyway, it's gone now. Thanks for flagging it.
