### ISSUE TITLE
csv sink doesn't handle sets correctly

### ISSUE THREAD

**Issue by pmos69** [mavam/vast#96]
Example:
For a set with these 2 strings: "aaa" and "bbb", the csv sink will output:
```"aaa"+"bbb"``` where + is the set separator.
This breaks csv compatibility because it has two double quoted values in a single field.

Output should be: ```"aaa+bbb"```
A better separator such as ``` | ``` (space + "|" +space) could probably be used as well, as discussed. (which could or could not be escaped with ```||``` for example).

**Comment by mavam** [comment]
For the ASCII sink, VAST should escape commas in strings, because commas delimit containers and records.

For the CSV sink, we should agree on a different set separator. Do you have a preference or know what's commonly used?

**Comment by pmos69** [comment]
CSV is a very limited format, and doesn't support the concept of sets within fields.
Here's the closest there is to a CSV standard: https://tools.ietf.org/html/rfc4180

I guess 2 logical options would be:
* Separate set elements with CRLF in a double quoted field (Not suported by splunk)
* Separate set elements with a ```, ``` or ``` | ``` or other readable indicator in a double quoted field.

Unfortunately, although Splunk supports multi-line records in csv when importing data for indexing through a specific option, that option is not present for the imput of csv data from external commands.

**Comment by mavam** [comment]
> Separate set elements with a , or | or other readable indicator in a double quoted field. something like: field1,"field2","set_field1_element1 | set_field1_element2"

I like `|` as set separator, it's visually quite clear. Per #95, the main issue is escaping. If `|` occurs within a string, how do we escape it? [RFC4180](https://tools.ietf.org/html/rfc4180) does not mention any escaping rules.

> Unfortunately, although Splunk supports multi-line records in csv when importing data for indexing through a specific option, that option is not present for the imput of csv data from external commands.

Isn't their SDK open source? If so, we could perhaps file a ticket or even a PR.

**Comment by pmos69** [comment]
Yes, RCF4180 is very basic (and so is csv).
Escaping in csv is absolutely not standard, although a few applications implement it for csv processing, allowing the definition of an escape character, but it's very uncommon.
Per RFC4180, a field may contain any character, as long as it's double-quote enclosed. In that situation, only " needs to be escaped and that's done simple by using "".
Since the initial focus of the csv sink was for splunk ingestion, maybe we can simplify things a bit and use ```||``` to escape the ```|``` character, the same way the double quote is escaped?
The handling of set fields is application dependent, anyway...
In Splunk, if there's a need to split a set field to do any set item processing, some simple processing is made over the field with built in functions. I guess other applications would have to do the same when receiving a set with any kind of encoding in a field.

**Comment by mavam** [comment]
> maybe we can simplify things a bit and use || to escape the | character, the same way the double quote is escaped?

I like that. Implemented in 3b5d3d5.

> One might even use a complex sequence of characters as a field separator, like <|>, |###|,|*|, |_|, or whatever, as long as it's not very common and is visually clear on its own it would be fine.

What gives me pause with this approach that it's not unambiguous: if a string contains this pattern, we're in trouble. That's why I think real escaping is the only possible strategy here.
